name: Windows Package python
on:
  push:
    branches:
    - main
jobs:
  auto-pack:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: install requirements
        run: pip install -r requirements.txt
      - name: Install pyinstaller
        run: pip install pyinstaller
      - name: pack exe file
        run: |
          pyinstaller --noconfirm --distpath output --onefile --console --add-data "./templates;templates/"  "./App.py"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: exe-file
          path: output/App.exe
      
        
    
